version: '3.7'

services:
  main:
    image: bloggapp.azurecr.io/gentle-blog:latest
    container_name: web_part
    volumes:
      - static:/app/staticfiles/
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
  nginx:
    container_name: server_part
    build: ./nginx
    volumes:
      - static:/app/staticfiles/
      - ./config/nginx/:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - main

volumes:
  static:
