# Generated by Django 3.1.5 on 2021-11-01 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('publish_date', models.DateField(auto_now=True, db_column='PublishDate')),
                ('text', models.CharField(db_column='Text', max_length=1500)),
                ('post_rating', models.FloatField(db_column='PostRating', null=True)),
                ('number_of_ratings', models.IntegerField(db_column='NumberOfRatings', null=True)),
                ('title', models.CharField(db_column='Title', max_length=500)),
                ('user', models.ForeignKey(db_column='User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
