# Generated by Django 3.2.7 on 2022-01-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211113_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(db_column='Text', max_length=5000),
        ),
    ]
